@endpoint = http://localhost:3000

@contentType = application/json

@accessToken = a.b.c


### get all player list
GET {{endpoint}}/dev/v1/players HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: {{contentType}}