@endpoint = http://localhost:3000

@contentType = application/json

### get all player list
GET {{endpoint}}/dev/v1/players HTTP/1.1
content-type: {{contentType}}



@playerId = UNX1KEX6Z

### get player profile
GET {{endpoint}}/dev/v1/players/{{playerId}} HTTP/1.1
content-type: {{contentType}}