@endpoint = http://localhost:3000

@contentType = application/json

@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwbGF5ZXJJZCI6IlVOWDFLRVg2WiIsImRpc3BsYXlOYW1lIjoiS2luZ2dvZGhvb24iLCJpYXQiOjE2ODk5MDMxNTAsImV4cCI6MTcyMTQ2MDc1MCwiaXNzIjoiVGFrZ2cifQ.YF3-k5kWhqDn-_OtmPVJ5MaykjLx3sZgiECnArCSr6Q

@playerId = UNX1KEX6Z

### get player profile
GET {{endpoint}}/dev/v1/players/{{playerId}} HTTP/1.1
Authorization: Bearer {{accessToken}}
content-type: {{contentType}}