swagger: "2.0"
info:
  title: Pinball API
  description: API for pinball game
  version: 1.0.0

host: mzgoi84by1.execute-api.ap-northeast-2.amazonaws.com
basePath: /dev/v1/pinball
schemes:
  - https
  
paths:
  ### LOGIN ###
  /login:
    post:
      summary: user login and store user data
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/LoginReq'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/LoginRes'
            
  ### GAME PLAY ###
  /play:
    # play start
    post:
      summary: game play start
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/gameStartReq'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/gamePlayRes'
    # play finish
    patch:
      summary: game play finish
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/gameFinishReq'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/gamePlayRes'
            
  ### GAME PLAY ###
  /rank:
    # play start
    post:
      summary: get rank list
      parameters:
        - in: body
          name: body
          required: true
          schema:
            $ref: '#/definitions/rankReq'
      responses:
        200:
          description: Success
          schema:
            $ref: '#/definitions/rankRes'
            
definitions:
  ### LOGIN ###
  # Login request
  LoginReq:
    properties:
      game_id:
        type: string
      player_id:
        type: string
      name:
        type: string
      image_url:
        type: string
      region:
        type: string
    required:  
      - game_id
      - player_id
      - name
      - image_url
      - region
  # Login response
  LoginRes:
    properties:
      result:
        type: boolean
      data:
        type: object
        properties:
          user_seq:
            type: number
          bestScore: 
            type: number
    required:  
      - result
  
  ### GAME PLAY ###
  # Play start request
  gameStartReq:
    properties:
      game_id:
        type: string
      user_seq:
        type: number
      context_id:
        type: string
        x-nullable: true
    required:
      - game_id
      - user_seq
      - context_id
  # Play finish request
  gameFinishReq:
    properties:
      play_seq:
        type: number
      score:
        type: number
    required:
      - play_seq
      - score
  # Play response
  gamePlayRes:
    properties:
      result:
        type: boolean
      data:
        type: object
        properties:
          play_seq:
            type: number
    required:  
      - result
      
  ### RANK ###
  # Rank request
  rankReq:
    properties:
      game_id:
        type: string
      user_seq:
        type: number
      player_id:
        type: array
        items: 
          type: string
        x-nullable: true
        
    required:  
      - game_id
      - user_seq
      - player_id
  # Rank response
  rankRes:
    properties:
      result:
        type: boolean
      data:
        type: object
        properties:
          rank:
            type: array
            items:
              type: object
              properties:
                rank: 
                  type: number
                player_id: 
                  type: string
                name: 
                  type: string
                score:
                  type: number
                image_url: 
                  type: string
                region:
                  type: string
                  x-nullable: true
          user: 
            type: object
            properties:
                rank: 
                  type: number
                player_id: 
                  type: string
                name: 
                  type: string
                score:
                  type: number
                image_url: 
                  type: string
                region:
                  type: string
                  x-nullable: true
          friends:
            type: array
            items:
              type: object
              properties:
                rank: 
                  type: number
                player_id: 
                  type: string
                name: 
                  type: string
                score:
                  type: number
                image_url: 
                  type: string
                region:
                  type: string
                  x-nullable: true
    required:  
      - result
      
      