@endpoint = http://localhost:3000

@contentType = application/json


### login
POST {{endpoint}}/dev/v1/players/auth/register HTTP/1.1
content-type: {{contentType}}

{
  "username": "string",
  "email": "string@test.co",
  "password": "password"
}
