POST https://slack.com/api/views.publish
Content-type: application/json
Authorization: Bearer [BOT TOKEN]

{
  "user_id": "[USER ID]",
  "view": {
	"type": "home",
	"blocks": [
		{
			"type": "header",
			"text": {
				"type": "plain_text",
				"text": "Hey, I'm a PlayDapp pingpong manager!:table_tennis_paddle_and_ball:",
				"emoji": true
			}
		},
		{
			"type": "header",
			"text": {
				"type": "plain_text",
				"text": "If you want authentication for mobile application,",
				"emoji": true
			}
		},
		{
			"type": "header",
			"text": {
				"type": "plain_text",
				"text": ":arrow_down:Click under button:arrow_down:",
				"emoji": true
			}
		},
		{
			"type": "actions",
			"elements": [
				{
					"type": "button",
					"text": {
						"type": "plain_text",
						"emoji": true,
						"text": "Get Auth Token :unlock:"
					},
					"value": "getAuthToken"
				}
			]
		}
	]
}
}